#!/usr/bin/env bash
#
# Kubest Docker Installer
#
# Usage:
#   ./install-docker.sh
#   ./install-docker.sh --kubeconfig /path/to/kubeconfig.yaml
#   ./install-docker.sh --port 9000
#   ./install-docker.sh --uninstall
#
set -euo pipefail

# Defaults
PORT="8000"
KUBECONFIG_FILE=""
SKIP_ENV=false
UNINSTALL=false

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${CYAN}[kubeast]${NC} $1"; }
ok()    { echo -e "${GREEN}[kubeast]${NC} $1"; }
warn()  { echo -e "${YELLOW}[kubeast]${NC} $1"; }
fail()  { echo -e "${RED}[kubeast]${NC} $1"; exit 1; }

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --kubeconfig)    KUBECONFIG_FILE="$2"; shift 2 ;;
    --port)          PORT="$2"; shift 2 ;;
    --skip-env)      SKIP_ENV=true; shift ;;
    --uninstall)     UNINSTALL=true; shift ;;
    --help|-h)
      echo "Kubest Docker Installer"
      echo ""
      echo "Usage: ./install-docker.sh [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --kubeconfig <path>  Path to kubeconfig file for target cluster"
      echo "  --port <port>        Gateway port (default: 8000)"
      echo "  --skip-env           Skip .env generation (use existing .env)"
      echo "  --uninstall          Stop and remove all containers/volumes"
      echo "  -h, --help           Show this help"
      exit 0
      ;;
    *) fail "Unknown option: $1" ;;
  esac
done

# ─── Uninstall ───
if [[ "$UNINSTALL" == "true" ]]; then
  info "Stopping Kubest..."
  cd "$ROOT"
  docker compose down -v 2>/dev/null || docker-compose down -v 2>/dev/null || true
  ok "Kubest has been removed (containers + volumes deleted)."
  exit 0
fi

# ─── Pre-flight checks ───
info "Checking prerequisites..."

if command -v docker compose >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  fail "docker compose not found. Install Docker Desktop or docker-compose: https://docs.docker.com/compose/install/"
fi

docker info >/dev/null 2>&1 || fail "Docker daemon is not running. Start Docker first."
ok "Docker is ready"

# ─── Kubeconfig ───
info "Setting up kubeconfig..."

if [[ -n "$KUBECONFIG_FILE" ]]; then
  if [[ ! -f "$KUBECONFIG_FILE" ]]; then
    fail "Kubeconfig not found: $KUBECONFIG_FILE"
  fi
  cp "$KUBECONFIG_FILE" "$ROOT/kubeconfig.yaml"
  ok "Kubeconfig copied from $KUBECONFIG_FILE"
elif [[ -f "$ROOT/kubeconfig.yaml" ]]; then
  ok "Using existing kubeconfig.yaml"
elif [[ -f "${KUBECONFIG:-$HOME/.kube/config}" ]]; then
  cp "${KUBECONFIG:-$HOME/.kube/config}" "$ROOT/kubeconfig.yaml"
  ok "Kubeconfig copied from ${KUBECONFIG:-$HOME/.kube/config}"
else
  warn "No kubeconfig found. k8s-service and tool-server will not be able to connect to a cluster."
  warn "You can add it later: cp /path/to/kubeconfig ./kubeconfig.yaml && docker compose restart k8s-service tool-server"
  touch "$ROOT/kubeconfig.yaml"
fi

# Resolve K8S API host/IP from kubeconfig for extra_hosts
K8S_API_HOST=""
K8S_API_IP=""
if [[ -s "$ROOT/kubeconfig.yaml" ]]; then
  API_SERVER=$(grep -oP 'server:\s*https?://\K[^:/]+' "$ROOT/kubeconfig.yaml" 2>/dev/null | head -1 || true)
  if [[ -n "$API_SERVER" ]]; then
    K8S_API_HOST="$API_SERVER"
    # Try to resolve IP
    RESOLVED_IP=$(getent hosts "$API_SERVER" 2>/dev/null | awk '{print $1}' | head -1 || \
                  dig +short "$API_SERVER" 2>/dev/null | head -1 || \
                  nslookup "$API_SERVER" 2>/dev/null | awk '/^Address: / { print $2 }' | head -1 || true)
    if [[ -n "$RESOLVED_IP" && "$RESOLVED_IP" != ";" ]]; then
      K8S_API_IP="$RESOLVED_IP"
      ok "K8s API: $API_SERVER -> $RESOLVED_IP"
    else
      warn "Could not resolve $API_SERVER. Set K8S_API_IP in .env manually."
    fi
  fi
fi

# ─── Generate .env ───
if [[ "$SKIP_ENV" == "true" && -f "$ROOT/.env" ]]; then
  ok "Using existing .env (--skip-env)"
else
  info "Generating .env file..."

  # Generate random passwords
  POSTGRES_PW=$(openssl rand -base64 18 | tr -dc 'a-zA-Z0-9' | head -c 20)
  ADMIN_PW=$(openssl rand -base64 18 | tr -dc 'a-zA-Z0-9' | head -c 20)

  # Preserve existing OPENAI_API_KEY if .env already exists
  EXISTING_API_KEY=""
  if [[ -f "$ROOT/.env" ]]; then
    EXISTING_API_KEY=$(grep '^OPENAI_API_KEY=' "$ROOT/.env" 2>/dev/null | cut -d= -f2- || true)
  fi
  OPENAI_KEY="${EXISTING_API_KEY:-your_openai_api_key_here}"

  cat > "$ROOT/.env" <<ENVEOF
# ─── Generated by install-docker.sh ───
# LLM
OPENAI_API_KEY=${OPENAI_KEY}
OPENAI_MODEL=gpt-4
# OPENAI_BASE_URL=

# Application
APP_NAME=Kubeast
APP_VERSION=1.0.0
DEBUG=false

# CORS
ALLOWED_ORIGINS=http://localhost:${PORT},http://localhost:5173

# Auth/JWT
JWT_ISSUER=kubeast-auth
JWT_AUDIENCE=kubeast
JWT_EXPIRES_MINUTES=10080
DEFAULT_ADMIN_EMAIL=admin
DEFAULT_ADMIN_PASSWORD=${ADMIN_PW}
KEY_DIR=/app/.keys

# Database
POSTGRES_USER=kubeast
POSTGRES_PASSWORD=${POSTGRES_PW}
POSTGRES_DB=kubeast

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0

# Kubernetes
KUBECONFIG_PATH=/app/kubeconfig.yaml
IN_CLUSTER=false
K8S_API_HOST=${K8S_API_HOST:-localhost}
K8S_API_IP=${K8S_API_IP:-127.0.0.1}

# Frontend
VITE_API_URL=http://localhost:${PORT}
VITE_WS_URL=ws://localhost:${PORT}
ENVEOF

  ok ".env generated (passwords auto-generated)"
fi

# ─── Update gateway port if non-default ───
if [[ "$PORT" != "8000" ]]; then
  info "Updating gateway port to $PORT..."
  # Override gateway port via env
  if ! grep -q '^GATEWAY_PORT=' "$ROOT/.env"; then
    echo "" >> "$ROOT/.env"
    echo "# Gateway port override" >> "$ROOT/.env"
    echo "GATEWAY_PORT=${PORT}" >> "$ROOT/.env"
  fi
fi

# ─── Build & Start ───
echo ""
echo -e "${BOLD}Starting Kubest...${NC}"
echo -e "  Gateway port: ${CYAN}${PORT}${NC}"
echo ""

cd "$ROOT"
$COMPOSE up -d --build 2>&1

# ─── Wait for services ───
info "Waiting for services to be healthy..."

wait_for_healthy() {
  local service="$1"
  local max_wait="${2:-60}"
  local elapsed=0
  while [[ $elapsed -lt $max_wait ]]; do
    local status
    status=$($COMPOSE ps --format json "$service" 2>/dev/null | grep -o '"Health":"[^"]*"' | cut -d'"' -f4 || echo "")
    if [[ "$status" == "healthy" ]]; then
      return 0
    fi
    sleep 2
    elapsed=$((elapsed + 2))
  done
  return 1
}

if wait_for_healthy postgres 60; then
  ok "PostgreSQL is healthy"
else
  warn "PostgreSQL may still be starting..."
fi

if wait_for_healthy redis 30; then
  ok "Redis is healthy"
else
  warn "Redis may still be starting..."
fi

# Wait a bit more for app services
sleep 3

# Quick check that gateway is responding
if curl -sf "http://localhost:${PORT}/health" >/dev/null 2>&1; then
  ok "Gateway is responding"
else
  warn "Gateway not responding yet. It may need a few more seconds."
fi

# ─── Access info ───
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║          Kubest is ready! (Docker)               ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Open: ${BOLD}http://localhost:${PORT}${NC}"
echo ""
echo "  Default account:"
echo "    ID:       admin"
ADMIN_PW_DISPLAY=$(grep '^DEFAULT_ADMIN_PASSWORD=' "$ROOT/.env" | cut -d= -f2-)
echo -e "    Password: ${BOLD}${ADMIN_PW_DISPLAY}${NC}"
echo -e "    ${YELLOW}!! Login 후 즉시 비밀번호를 변경하세요.${NC}"
echo ""
echo "  Next steps:"
echo "    1. Open the URL above"
echo "    2. Sign in with admin account"
echo "    3. Go to Admin > AI Models to add your AI provider"
echo ""
echo -e "  Logs:      ${CYAN}docker compose logs -f${NC}"
echo -e "  Stop:      ${CYAN}docker compose down${NC}"
echo -e "  Uninstall: ${CYAN}./install-docker.sh --uninstall${NC}"
echo ""
